name: Check URLs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5"

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check URLs
      run: |
          curl -LO 'https://github.com/lycheeverse/lychee/releases/download/v0.10.0/lychee-v0.10.0-x86_64-unknown-linux-gnu.tar.gz'
          tar -xvzf lychee-v0.10.0-x86_64-unknown-linux-gnu.tar.gz
          chmod +x lychee
          ./lychee "content/*/*/*.md" --no-progress --verbose --require-https
      env:
        CLICOLOR_FORCE: 1
