name: URLs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1-5"

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose --require-https --include-fragments 'content/*/*/*.md' --max-retries 0 --max-concurrency 1
          fail: true
        env:
          CLICOLOR_FORCE: 1
