name: Deploy and sync search index

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZENDESK_USER: ${{ secrets.ZENDESK_USER }}
      ZENDESK_PASS: ${{ secrets.ZENDESK_TOKEN }}
      ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      ALGOLIA_INDEXER_KEY: ${{ secrets.ALGOLIA_INDEXER_KEY }}
      ALGOLIA_INDEX: ${{ secrets.ALGOLIA_INDEX }}

    steps:
      - uses: actions/checkout@master

      - name: Sync
        run: |
          cd _deploy
          npm install
          cd ..
          node _deploy/zendesk.mjs content '*/*/*.md' https://arduino.zendesk.com/api/v2/help_center --wait 60 --deploy --syncIndex
